---
engines:
  lizard:
    enabled: true
  eslint:
    enabled: true
  cppcheck:
    enabled: true
  semgrep:
    enabled: true
  htmlhint:
    enabled: true

exclude_paths:
  - 'coolerdash-bin/*'
  - 'build/**'
  - 'bin/**'
  - '**.pkg.tar.zst'
