#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if command -v systemctl >/dev/null 2>&1; then
            if systemctl is-active --quiet coolercontrold.service; then
                systemctl restart coolercontrold.service || echo "Note: CoolerControl restart failed."
            fi
        elif command -v rc-service >/dev/null 2>&1 && [ -x /etc/init.d/coolercontrold ]; then
            if rc-service coolercontrold status >/dev/null 2>&1; then
                rc-service coolercontrold restart || echo "Note: CoolerControl restart failed."
            fi
        fi
        ;;
esac

#DEBHELPER#

exit 0
